//SystemSetting
export const SET_DASHBOARD = 'SET_DASHBOARD'
export const SET_CONFIG = 'SET_CONFIG'
export const SET_CONFIG_KEY = 'SET_CONFIG_KEY'
export const SET_LEFT_SIDEBAR_CONFIG = 'SET_LEFT_SIDEBAR_CONFIG'
export const SET_PALETTE = 'SET_PALETTE'
export const RESET_PALETTES = 'RESET_PALETTES'

//role
export const SEARCH_ROLE_RESULT = 'SEARCH_ROLE_RESULT'
export const GET_ROLE = 'GET_ROLE'
export const GET_ALL_FUNCTIONS = 'GET_ALL_FUNCTIONS'


//Common
export const API_ERROR = "API_ERROR"
export const API_SUCCESS = "API_SUCCESS"
export const SET_LOADING = "SET_LOADING"
export const GET_PARAM_TYPES = 'GET_PARAM_TYPES'
export const GET_COMMON_PARAM = 'GET_COMMON_PARAM'
export const GET_ENQUIRY_PARAM_TYPES = 'GET_ENQUIRY_PARAM_TYPES'
export const GET_ENQUIRY_PARAM = 'GET_ENQUIRY_PARAM'
export const GET_EMSG_MATCH_STATUSES = 'GET_EMSG_MATCH_STATUSES'
export const GET_RTP_FREQUENCIES = 'GET_RTP_FREQUENCIES'
export const GET_SYSTEM_ROLES = 'GET_SYSTEM_ROLES'
export const GET_MG_USERS = 'GET_MG_USERS'

//member(it means login user)
export const SET_AUTH_DATA = 'SET_AUTH_DATA'
export const GET_MENU = 'GET_MENU'
export const SEARCH_USER = 'SEARCH_USER'
export const SET_USER_CRITERIA = 'SET_USER_CRITERIA'
export const RESET_USER_CRITERIA = 'RESET_USER_CRITERIA'
export const GET_USER_INFO = 'GET_USER_INFO'

//user(通常表示會員)
export const ADMIN_USER_LOGIN = 'ADMIN_USER_LOGIN'

//般舶資料管理
//ship
export const GET_VESSEL = 'GET_VESSEL'
export const SEARCH_VESSEL = 'SEARCH_VESSEL'
export const SET_VESSEL_CRITERIA = 'SET_VESSEL_CRITERIA'
export const RESET_VESSEL_CRITERIA = 'RESET_VESSEL_CRITERIA'
export const NEW_VESSEL = 'NEW_VESSEL'
export const SEARCH_VESSEL_BY_NAME = 'SEARCH_VESSEL_BY_NAME'
export const GET_VESSEL_TYPES = 'GET_VESSEL_TYPES'
//setting
export const SEARCH_PARAMS = 'SEARCH_PARAMS'
export const SET_PARAM_CRITERIA = 'SET_PARAM_CRITERIA'
export const RESET_PARAM_CRITERIA = 'RESET_PARAM_CRITERIA'
export const GET_PARAM = 'GET_PARAM'
//trade成交價
export const GET_VESSEL_SP_INFO = 'GET_VESSEL_SP_INFO'
export const GET_VESSEL_SP_RECORDS = 'GET_VESSEL_SP_RECORDS'
export const GET_VESSEL_EV_INFO = 'GET_VESSEL_EV_INFO'
export const GET_VESSEL_EV_RECORDS = 'GET_VESSEL_EV_RECORDS'
//vessel-emsg
export const GET_VESSEL_EMSGS = 'GET_VESSEL_EMSGS'
//vessel-attachment
export const GET_VESSEL_ATTACHES = 'GET_VESSEL_ATTACHES'



//customer
export const SEARCH_CUSTOMER = 'SEARCH_CUSTOMER'
export const SET_CUSTOMER_CRITERIA = 'SET_CUSTOMER_CRITERIA'
export const RESET_CUSTOMER_CRITERIA = 'RESET_CUSTOMER_CRITERIA'
export const GET_CUSTOMER = 'GET_CUSTOMER'

//成交行情管理
export const SEARCH_ESTIMATE = 'SEARCH_ESTIMATE'
export const SET_ESTIMATE_CRITERIA = 'SET_ESTIMATE_CRITERIA'
export const RESET_ESTIMATE_CRITERIA = 'RESET_ESTIMATE_CRITERIA'
export const SEARCH_TRADE = 'SEARCH_TRADE'
export const SET_TRADE_CRITERIA = 'SET_TRADE_CRITERIA'
export const RESET_TRADE_CRITERIA = 'RESET_TRADE_CRITERIA'
export const SEARCH_VESSEL_EST = 'SEARCH_VESSEL_EST'
export const SET_VESSEL_EST_CRITERIA = 'SET_VESSEL_EST_CRITERIA'
export const RESET_VESSEL_EST_CRITERIA = 'RESET_VESSEL_EST_CRITERIA'
export const GET_VESSEL_EST = 'GET_VESSEL_EST'
export const SEARCH_DEMOLITION = 'SEARCH_DEMOLITION'
export const SET_DEMO_CRIT = 'SET_DEMO_CRIT'
export const RESET_DEMO_CRIT = 'RESET_DEMO_CRIT'


//setting-enquiry
export const SEARCH_ENQUIRY = 'SEARCH_ENQUIRY'
export const SET_ENQUIRY_CRITERIA = 'SET_ENQUIRY_CRITERIA'
export const RESET_ENQUIRY_CRITERIA = 'RESET_ENQUIRY_CRITERIA'
export const GET_ENQUIRY_PARAM_INFO = 'GET_ENQUIRY_PARAM_INFO'
//setting-mail-group
export const SEARCH_MAIL_GROUP ='SEARCH_MAIL_GROUP'
export const SET_MAIL_GROUP_CRITERIA = 'SET_MAIL_GROUP_CRITERIA'
export const RESET_MAIL_GROUP_CRITERIA = 'RESET_MAIL_GROUP_CRITERIA'
export const GET_MAIL_GROUP_INFO = 'GET_MAIL_GROUP_INFO'
export const GET_MINE_MAIL_GROUP = 'GET_MINE_MAIL_GROUP'

//電文管理
export const SEARCH_EMSG = 'SEARCH_EMSG'
export const SET_EMSG_CRITERIA = 'SET_EMSG_CRITERIA'
export const RESET_EMSG_CRITERIA = 'RESET_EMSG_CRITERIA'
export const GET_EMSG_INFO = 'GET_EMSG_INFO'

//船舶需求管理
export const SEARCH_ENQUIRY_LIST = 'SEARCH_ENQUIRY_LIST'
export const SET_ENQUIRY_LIST_CRITERIA = 'SET_ENQUIRY_LIST_CRITERIA'
export const RESET_ENQUIRY_LIST_CRITERIA = 'RESET_EQNUIRY_LIST_CRITERIA'
export const GET_ENQUIRY_INFO = 'GET_ENQUIRY_INFO'

//報表sp
export const SET_RPT_SP_CRITERIA = 'SET_RPT_SP_CRITERIA'
export const RESET_PRT_SP_CRITERIA = 'RESET_PRT_SP_CRITERIA'
export const SET_SP_DATASET = 'SET_SP_DATASET'
//ev
export const SET_RPT_EV_CRITERIA = 'SET_RPT_EV_CRITERIA'
export const RESET_RPT_EV_CRITERIA = 'RESET_RPT_EV_CRITERIA'
export const SET_EV_DATASET = 'SET_EV_DATASET'
//demolition
export const SET_RPT_DEMOLITION_CRIT = 'SET_RTP_DEMOLITION_CRIT'
export const RESET_RPT_DEMOLITION_CRIT = 'RESET_RPT_DEMOLITION_CRIT'
export const SET_DEMOLITION_DATASET = 'SET_DEMOLITION_DATASET'
//est
export const SET_RPT_EST_CRITERIA = 'SET_RPT_EST_CRITERIA'
export const RESET_RPT_EST_CRITERIA = 'RESET_RPT_EST_CRITERIA'
export const SET_EST_DATASET = 'SET_EST_DATASET'


